### ISSUE TITLE
[Feat] 가게 API

### ISSUE THREAD

**Issue by kyungjinleelee** [Bab-doduk/Backend#1]
## TODO
- [x] 테이블 생성
- [x] 컨트롤러 작성
- [x] 레포지토리 파일 작성
- [x] 서비스 파일 작성
    - [x] 가게 CRUD 기능
    - [x] 가게 Search 기능
