### ISSUE TITLE
[refactor] 유저 권한 인증/인가 리팩토링

### ISSUE THREAD

**Issue by kyungjinleelee** [Bab-doduk/Backend#12]
## TODO
- [x] 결제 API 리팩토링
    - [x] 결제 CRD기능
- [x] 가게 API 리팩토링
    - [x] 가게 CRUD기능
    - [x] 가게 Search 기능
