### ISSUE TITLE
[Feat] Custom 예외 처리, 응답 형식 통일

### ISSUE THREAD

**Issue by kyungjinleelee** [Bab-doduk/Backend#4]
## TODO
- [x] Custom 예외 처리
  - [x] CustomException 파일 생성
  - [x] ErrorCode 파일 생성 (에러 코드 커스텀)
  - [x] ErrorResponse 파일 생성
  - [x] GlobalExceptionHandler 파일 생성
- [x] 응답 형식 통일
  - [x] ApiResponseDto 파일 생성
