### ISSUE TITLE
[Feat] 결제 API 

### ISSUE THREAD

**Issue by kyungjinleelee** [Bab-doduk/Backend#5]
## TODO
- [x] 테이블 작성
- [x] 컨트롤러 작성
- [x] 레포지토리 파일 작성
- [x] 서비스 파일 작성
    - [x] 결제 CRUD 기능
    - [x] 결제 Search 기능
